
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'DBT_First_Model'
version: '1.0.0'

profile: 'DBT_First_Model'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  DBT_First_Model:

    staging:
      +materialized: incremental
      +database: SALES_DBT_DB
      +schema: STG

    intermediate:
      +materialized: incremental
      +database: SALES_DBT_DB
      +schema: WI

    marts:
      +materialized: incremental
      +database: SALES_DBT_DB
      +schema: MART