{{ config(
    materialized='table'
) }}

WITH dates AS (
    SELECT DISTINCT
        ORDER_DATE
    FROM {{ ref('stg_sales_order') }}
)

SELECT
    TO_NUMBER(TO_CHAR(ORDER_DATE,'YYYYMMDD')) AS DATE_KEY,
    ORDER_DATE AS CALENDAR_DATE,
    DAY(ORDER_DATE) AS DAY_NUMBER,
    MONTH(ORDER_DATE) AS MONTH_NUMBER,
    MONTHNAME(ORDER_DATE) AS MONTH_NAME,
    QUARTER(ORDER_DATE) AS QUARTER_NUMBER,
    YEAR(ORDER_DATE) AS YEAR_NUMBER,
    WEEK(ORDER_DATE) AS WEEK_NUMBER
FROM dates